### ISSUE TITLE
Custom GitHub action

### ISSUE THREAD

**Issue by dahlia** [dahlia/submark#6]
<https://docs.github.com/en/actions/creating-actions>

Considering `submark`'s main use cases, it would be much useful if it is distributed as a GitHub action too.  It should look like:

```yaml
- id: submark
  if: github.ref_type == 'tag'
  uses: dahlia/submark@0.3.0
  with:
    input-file: CHANGES.md
    heading-level: 2
    heading-text: Version ${{ github.ref_name }}
    ignore-case: true
    omit-heading: true

- if: github.ref_type == 'tag'
  uses: softprops/action-gh-release@v1
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    body: ${{ steps.submark.outputs.output-text }}
    name: Foo ${{ github.ref_name }}
    files: dist/foo-${{ github.ref_name }}.tar.gz
```

**Comment by dahlia** [comment]
Before building the `dahlia/submark` action, it'd be better to build the `dahlia/submark/setup` action first, as a smaller building block:

```yaml
- uses: dahlia/submark/setup@0.3.0
  with:
    submark-version: 0.3.*
    add-to-path: true
```

I believe both actions can be implemented by [compositing actions][1].

[1]: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
